# Changes here will be overwritten by Copier
_commit: a2d5d1c
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: false
copyright_year: '2023'
documentation: false
email: nick@koston.org
full_name: J. Nick Koston
github_username: bdraco
has_cli: false
initial_commit: true
open_source_license: MIT
package_name: cached_ipaddress
project_name: cached-ipaddress
project_short_description: Cache construction of ipaddress objects
project_slug: cached-ipaddress
run_poetry_install: true
setup_github: true
setup_pre_commit: true

